### ISSUE TITLE
Custom Baude Rate

### ISSUE THREAD

**Issue by Maxim-Issaev** [fightforlife/ESP32_TWAI_Arduino#1]
Is it real to set can bus speed to 95 kb/s?

**Comment by fightforlife** [comment]
Hi Maxim, this repo is still work in progress. I will work on it this weekend.
Custom baudrate will not be the first priority, but it should be possible.
Check out the following links:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html#bit-timing
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html#_CPPv420twai_timing_config_t
